version: '3.1'

services:

  db:
    image: postgres
    restart: always
    volumes: 
          - ./docker/db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: hotel
    ports: 
       - 5432:5432  